# Use the official Jupyter base image jupyter/datascience-notebook:latest
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the contents of the local directory to /app in the container
#COPY app.py /app/

# Copy the updated requirements.txt into the container
COPY requirements.txt /app/requirements.txt

# Copy the .env file into the container
#COPY .env /app/.env

# Set a volume for the working directory
VOLUME /app

# Install any additional dependencies (if needed)
RUN pip install --no-cache-dir -r /app/requirements.txt

# Install the Neo4j Python driver
RUN pip install --no-cache-dir neo4j==4.0.0
RUN pip install --no-cache-dir pymongo

# Expose port 5000 to the outside world
EXPOSE 5000

# Run app.py when the container launches
#CMD ["python", "app.py"]
CMD ["uvicorn", "entrypoint.app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
