version: '3.3'

services:
  neo4j:
    image: neo4j:5.13
    container_name: my-neo4j-container
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ../data/profiling:/import  # Mount a volume for the import directory 
    environment:
      NEO4J_AUTH: neo4j/password  # Set your desired password
    networks:
      - neo4j-network  # If you want to use a Docker network
  mongodb:
    image: mongo:latest
    container_name: evalu8-mongodb
    ports:
      - "27017:27017"
#    volumes:
#      - ../data/kpi/data/db:/data/db
#    command: mongod --dbpath /data/db
    networks:
      - neo4j-network
  evalu8-app:
    container_name: evalu8-app
    build:
      context: ..
      dockerfile: Dockerfile  # Your application's Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - "../:/app"  
    depends_on:
      - neo4j
      - mongodb
    networks:
      - neo4j-network  # If you want your app to communicate with Neo4j on the same network
  evalu8-web:
    container_name: evalu8-web
    build:
      context: ..
      dockerfile: Dockerfile_web 
    volumes:
      - "../:/app"
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
      - mongodb
    networks:
      - neo4j-network  # If you want your app to communicate with Neo4j on the same network
networks:
  neo4j-network:
    driver: bridge
